name: Schedule Update and Deploy to Firebase Hosting

on:
  schedule:
    - cron: '*/5 * * * *'  # Каждые 5 минут
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Проверка репозитория
      - uses: actions/checkout@v4

      # Запуск скрипта обновления
      - run: node sheduleUpdate.js

      # Деплой в Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RADIO_RADONEZH }}
          projectId: radio-radonezh
          channelId: live
